<h1>Neural Network from scratch </h1>

### Each row is a training example, each column is a feature  [f1, f2, f3]
X=[0,0,1],[0,1,1],[1,0,1],[1,1,1]
y=[0],[1],[1],[0])

In [1]:
#Initializing x and y with numpy
import numpy as np
X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)

<h3>Activation Function </h1>

In [2]:
# sigmoid  function
def sigmoid(t):
    '''This will return the sigmoid value of the function'''
    return 1/(1+np.exp(-t))


In [3]:
# derivative sigmoid
def sigmoid_derivative(d):
    return d * (1 - d)


In [17]:
# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x #initializing x
        self.weights1= np.random.rand(self.input.shape[1],4) #initializing random weights
        self.weights2 = np.random.rand(4,1)#considering we have 4 nodes in the hidden layer
        self.y = y#initializing y
        self.output = np. zeros(y.shape)#initializing the output
        
    def feedforward(self):
        '''This will perform the forward propagation for the next 2 layers'''
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))#calcuation of w_T*X+b for layer1
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))#calcuation of w_T*X+b for layer2
        return self.layer2
        
    def backprop(self,iter):
        '''Back propagation of the final hidden layers to initial layers'''
        derv_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))#backpropagation of layer2
        derv_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += 1.0/iter * derv_weights1#updation of weight matrix of layer1
        self.weights2 += 1.0/iter * derv_weights2#updation of weight matrix of layer2

    def train(self, X, y,iter):
        self.output = self.feedforward()#Forward Propagation
        self.backprop(iter)#Backward Propagation

In [19]:
model=NeuralNetwork(X,y)
for i in range(1500):
    if i % 100 ==0:#For each 100 epochs output will come 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(model.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - model.feedforward())))) # mean sum squared loss
        print ("\n")
  
    model.train(X, y,i+1)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.84783431]
 [0.90308169]
 [0.87245383]
 [0.91324168]]
Loss: 
0.39462364061157723


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.50203269]
 [0.53292958]
 [0.48506854]
 [0.51321791]]
Loss: 
0.24968465745290835


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.49970052]
 [0.53028474]
 [0.48260163]
 [0.51034715]]
Loss: 
0.2496220829474417


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.49890479]
 [0.52944503]
 [0.48181936]
 [0.5094452 ]]
Loss: 
0.24959338976303758


for iteration # 400

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [